### ISSUE TITLE
Improve match "match" algorithm to be more generic

### ISSUE THREAD

**Issue by vsoch** [converged-computing/rainbow#23]
We currently require that we are matching a "type" - which I did just to keep it simple. That looks like this:

```yaml
version: 1
resources:
- count: 2
  type: node
  with:
  - count: 1
    label: default
    type: slot
    with:
    - count: 2
      type: core
task:
  command:
  - ior
  slot: default
  count:
    per_slot: 1
  resources:
    io:
      match:
      - type: shm
```
This can easily be improved upon to:

1. be more generic (not just type)
2. allow for more than one match entry

So I'm going to update it to be like:

```yaml
version: 1
resources:
- count: 2
  type: node
  with:
  - count: 1
    label: default
    type: slot
    with:
    - count: 2
      type: core
task:
  command:
  - ior
  slot: default
  count:
    per_slot: 1
  resources:
    io:
      match:
      - field: type
        value: shm
```
It's mostly the same, but gives the user freedom to match something else, and (I suppose it was already a listing) to match more than one thing.
